#! /usr/bin/python
import os
import time
from sys import argv, exit

try:
	argv[1]
except IndexError:
	print "Give at least one file"
	exit(1)
else:
	file_to_watch = {'name': argv[1]}
	temp_stat = os.stat(file_to_watch['name'])

file_to_watch['last_mod_time'] = temp_stat.st_ctime

try:
	argv[2]
except IndexError:
	file_to_generate = "%s.html" % file_to_watch['name'].split('.')[0]
else:
	file_to_generate = argv[2]

wait_display = 0

while True:
    mod_time = os.stat(file_to_watch['name']).st_ctime
	
    if (wait_display == 0):
        print "Watching for changes"
        wait_display = 1

    if (mod_time == file_to_watch['last_mod_time']):
        try:
			time.sleep(1)
        except KeyboardInterrupt:
            print "\nEnding watch"
            exit(1)
    else:
        print "Changes detected..."
        pd_string = 'pandoc %s -o %s' % (file_to_watch['name'], file_to_generate)
        os.system(pd_string)
        file_to_watch['last_mod_time'] = mod_time
        wait_display = 0
